Созданы компоненты страниц
htmlacademy-react/2547343-six-cities-16 pull request #2
Opened 2024-07-08 15:40 UTC by faviru

2024-07-08 16:25 UTC, baileys-li requested changes

2024-07-08 16:25 UTC, baileys-li commented on src/components/App.tsx
> +import MainScreen from '../pages/main';
У вас есть критерий про названия файлов с маленькой буквы
(мне самому непривычно, но лучше поправить сейчас)

2024-07-08 17:39 UTC, faviru commented on src/components/App.tsx
> +import MainScreen from '../pages/main';
Точно, спасибо)

2024-07-10 15:26 UTC, baileys-li requested changes
Нужно ещё связать ПР с заданием в интерфейсе академии

2024-07-10 15:26 UTC, baileys-li commented on src/components/header/header.tsx
> +  isNavigation: boolean;
Nit: лучше читается кмк
```suggestion
  hasNavigation: boolean;
```

2024-07-10 15:26 UTC, baileys-li commented on src/components/App.tsx
> +    <MainScreen placeCardsCount={props.placeCardsCount} cities={props.cities} isNavigation={props.isNavigation} />
Лучше деструктуизировать
```suggestion
function App({placeCardsCount, cities, isNavigation}: AppProps): JSX.Element {
  return (
    <MainScreen placeCardsCount={placeCardsCount} cities={cities} isNavigation={isNavigation} />
```

2024-07-10 15:26 UTC, baileys-li commented on src/components/locations-list/locations-list.tsx
> +  const List = cities.map((item: string) => <LocationItem city={item} key={item} />);
Ну это не класс, и не FC
```suggestion
  const list = cities.map((item: string) => <LocationItem city={item} key={item} />);
```

2024-07-10 15:26 UTC, baileys-li commented on src/components/App.tsx
> -function App({ placeCardsCount }: AppProps): JSX.Element {
Не вышло обновить файл, скорее всего из-за того, как гит на винде не реагирует на регистр. Попробуй сначала закоммитить удаление этого файла, а потом закоммитить такой же файл на с другим названием

2024-07-10 16:49 UTC, baileys-li commented on src/components/App.tsx
> +import MainScreen from '../pages/main';
Не вышло обновить файл. Такое случается на Windows. Попробуй закоммитить удаление, а потом закоммить новый файл с таким же контентом, но с маленькой буквы

2024-07-11 10:27 UTC, merged